language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE="nocrypto"
    - UPDATE_GCC_BINUTILS=1
  matrix:
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.02 DEPOPTS="lwt cstruct-lwt"
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.03 DEPOPTS="lwt cstruct-lwt"
    - OCAML_VERSION=4.03 DEPOPTS="mirage-entropy" TESTS=false
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.04 DEPOPTS="lwt cstruct-lwt"
    - OCAML_VERSION=4.04 DEPOPTS="mirage-xen" TESTS=false
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.05 DEPOPTS="lwt cstruct-lwt"
    - OCAML_VERSION=4.05 DEPOPTS="mirage-solo5 mirage-entropy" TESTS=false
notifications:
  email: false
